In [1]:
# Importing all the necessary libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
# Using this approach of specifying Latin-1 encoding because I got the UnicodeDecodeError when I tried reading it without unicode specification
# This means that the csv file has characters which are incompatible with UTF-8
# It also works for CP1252 encoding
try:
    df = pd.read_csv("cancer_reg.csv")  # Try to read the csv file with UTF-8
except UnicodeDecodeError:
    df = pd.read_csv("cancer_reg.csv", encoding="Latin-1")  # Try to read the csv file with Latin-1 encoding
df

,avgAnnCount,avgDeathsPerYear,TARGET_deathRate,incidenceRate,medIncome,popEst2015,povertyPercent,studyPerCap,binnedInc,MedianAge,...,PctPrivateCoverageAlone,PctEmpPrivCoverage,PctPublicCoverage,PctPublicCoverageAlone,PctWhite,PctBlack,PctAsian,PctOtherRace,PctMarriedHouseholds,BirthRate
0,1397.000000,469,164.9,489.800000,61898,260131,11.2,499.748204,"(61494.5, 125635]",39.3,...,NaN,41.6,32.9,14.0,81.780529,2.594728,4.821857,1.843479,52.856076,6.118831
1,173.000000,70,161.3,411.600000,48127,43269,18.6,23.111234,"(48021.6, 51046.4]",33.0,...,53.8,43.6,31.1,15.3,89.228509,0.969102,2.246233,3.741352,45.372500,4.333096
2,102.000000,50,174.7,349.700000,49348,21026,14.6,47.560164,"(48021.6, 51046.4]",45.0,...,43.5,34.9,42.1,21.1,90.922190,0.739673,0.465898,2.747358,54.444868,3.729488
3,427.000000,202,194.8,430.400000,44243,75882,17.1,342.637253,"(42724.4, 45201]",42.8,...,40.3,35.0,45.3,25.0,91.744686,0.782626,1.161359,1.362643,51.021514,4.603841
4,57.000000,26,144.4,350.100000,49955,10321,12.5,0.000000,"(48021.6, 51046.4]",48.3,...,43.9,35.1,44.0,22.7,94.104024,0.270192,0.665830,0.492135,54.027460,6.796657
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3042,1962.667684,15,149.6,453.549422,46961,6343,12.4,0.000000,"(45201, 48021.6]",44.2,...,54.9,44.6,31.7,13.2,90.280811,3.837754,0.327613,1.700468,51.063830,7.773512
3043,1962.667684,43,150.1,453.549422,48609,37118,18.8,377.175494,"(48021.6, 51046.4]",30.4,...,53.3,48.6,28.8,17.7,75.706245,2.326771,4.044920,14.130288,52.007937,8.186470
3044,1962.667684,46,153.9,453.549422,51144,34536,15.0,1968.959926,"(51046.4, 54545.6]",30.9,...,52.6,47.8,26.6,16.8,87.961629,2.313188,1.316472,5.680705,55.153949,7.809192
3045,1962.667684,52,175.0,453.549422,50745,25609,13.3,0.000000,"(48021.6, 51046.4]",39.0,...,56.3,49.6,29.5,14.0,92.905681,1.176562,0.244632,2.131790,58.484232,7.582938
3046,1962.667684,48,213.6,453.549422,41193,37030,13.9,0.000000,"(40362.7, 42724.4]",26.2,...,60.3,22.9,25.1,12.6,70.098132,16.590100,3.177753,1.356457,56.040242,8.981723

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3047 entries, 0 to 3046
Data columns (total 34 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   avgAnnCount              3047 non-null   float64
 1   avgDeathsPerYear         3047 non-null   int64
 2   TARGET_deathRate         3047 non-null   float64
 3   incidenceRate            3047 non-null   float64
 4   medIncome                3047 non-null   int64
 5   popEst2015               3047 non-null   int64
 6   povertyPercent           3047 non-null   float64
 7   studyPerCap              3047 non-null   float64
 8   binnedInc                3047 non-null   object
 9   MedianAge                3047 non-null   float64
 10  MedianAgeMale            3047 non-null   float64
 11  MedianAgeFemale          3047 non-null   float64
 12  Geography                3047 non-null   object
 13  AvgHouseholdSize         3047 non-null   float64
 14  PercentMarried           3047 non-null   float64
 15  PctNoHS18_24             3047 non-null   float64
 16  PctHS18_24               3047 non-null   float64
 17  PctSomeCol18_24          762 non-null    float64
 18  PctBachDeg18_24          3047 non-null   float64
 19  PctHS25_Over             3047 non-null   float64
 20  PctBachDeg25_Over        3047 non-null   float64
 21  PctEmployed16_Over       2895 non-null   float64
 22  PctUnemployed16_Over     3047 non-null   float64
 23  PctPrivateCoverage       3047 non-null   float64
 24  PctPrivateCoverageAlone  2438 non-null   float64
 25  PctEmpPrivCoverage       3047 non-null   float64
 26  PctPublicCoverage        3047 non-null   float64
 27  PctPublicCoverageAlone   3047 non-null   float64
 28  PctWhite                 3047 non-null   float64
 29  PctBlack                 3047 non-null   float64
 30  PctAsian                 3047 non-null   float64
 31  PctOtherRace             3047 non-null   float64
 32  PctMarriedHouseholds     3047 non-null   float64
 33  BirthRate                3047 non-null   float64
dtypes: float64(29), int64(3), object(2)
memory usage: 809.5+ KB

In [4]:
df.describe()

,avgAnnCount,avgDeathsPerYear,TARGET_deathRate,incidenceRate,medIncome,popEst2015,povertyPercent,studyPerCap,MedianAge,MedianAgeMale,...,PctPrivateCoverageAlone,PctEmpPrivCoverage,PctPublicCoverage,PctPublicCoverageAlone,PctWhite,PctBlack,PctAsian,PctOtherRace,PctMarriedHouseholds,BirthRate
count,3047.000000,3047.000000,3047.000000,3047.000000,3047.000000,3.047000e+03,3047.000000,3047.000000,3047.000000,3047.000000,...,2438.000000,3047.000000,3047.000000,3047.000000,3047.000000,3047.000000,3047.000000,3047.000000,3047.000000,3047.000000
mean,606.338544,185.965868,178.664063,448.268586,47063.281917,1.026374e+05,16.878175,155.399415,45.272333,39.570725,...,48.453774,41.196324,36.252642,19.240072,83.645286,9.107978,1.253965,1.983523,51.243872,5.640306
std,1416.356223,504.134286,27.751511,54.560733,12040.090836,3.290592e+05,6.409087,529.628366,45.304480,5.226017,...,10.083006,9.447687,7.841741,6.113041,16.380025,14.534538,2.610276,3.517710,6.572814,1.985816
min,6.000000,3.000000,59.700000,201.300000,22640.000000,8.270000e+02,3.200000,0.000000,22.300000,22.400000,...,15.700000,13.500000,11.200000,2.600000,10.199155,0.000000,0.000000,0.000000,22.992490,0.000000
25%,76.000000,28.000000,161.200000,420.300000,38882.500000,1.168400e+04,12.150000,0.000000,37.700000,36.350000,...,41.000000,34.500000,30.900000,14.850000,77.296180,0.620675,0.254199,0.295172,47.763063,4.521419
50%,171.000000,61.000000,178.100000,453.549422,45207.000000,2.664300e+04,15.900000,0.000000,41.000000,39.600000,...,48.700000,41.100000,36.300000,18.800000,90.059774,2.247576,0.549812,0.826185,51.669941,5.381478
75%,518.000000,149.000000,195.200000,480.850000,52492.000000,6.867100e+04,20.400000,83.650776,44.000000,42.500000,...,55.600000,47.700000,41.550000,23.100000,95.451693,10.509732,1.221037,2.177960,55.395132,6.493677
max,38150.000000,14010.000000,362.800000,1206.900000,125635.000000,1.017029e+07,47.400000,9762.308998,624.000000,64.700000,...,78.900000,70.700000,65.100000,46.600000,100.000000,85.947799,42.619425,41.930251,78.075397,21.326165

In [5]:
# Finding the columns with null values
null_columns = df.columns[df.isnull().any()]

# Finding the count of null values in each of the columns
null_counts = df[null_columns].isnull().sum()

# Printing the columns with null values and their counts
print(null_counts)

PctSomeCol18_24            2285
PctEmployed16_Over          152
PctPrivateCoverageAlone     609
dtype: int64

In [6]:
# Dropping the PctSomeCol18_24 column as around 75% of the data is null
df=df.drop('PctSomeCol18_24', axis=1)

In [7]:
# Calculating median of the data in PctEmployed16_Over column and replacing the null values with the resulting median value
df['PctEmployed16_Over'].fillna(df['PctEmployed16_Over'].median(), inplace=True)

In [8]:
# Calculating median of the data in PctPrivateCoverageAlone column and replacing the null values with the resulting median value
df['PctPrivateCoverageAlone'].fillna(df['PctPrivateCoverageAlone'].median(), inplace=True)

In [9]:
# Calculating the number of unique values in the Geography column to assess if encoding is possible for this categorical feature
unique_values = df["Geography"].nunique()
print(unique_values)

3047

In [10]:
# Dropping the Geography column as all the data in the column are unique
df = df.drop('Geography', axis=1)

In [11]:
# Using Midpoint Transformation to convert binned data into numerical data
# Function to calculate the midpoint of the binnedInc data samples
def get_midpoint(binned_value):
    # Removing square brackets and open parentheses and closing square bracket and splitting by comma
    binned_value = binned_value.strip('[](])').split(',')
    lower_bound = float(binned_value[0])
    upper_bound = float(binned_value[1])

    # Calculating and returning the midpoint
    return (lower_bound + upper_bound) / 2

# Applying the midpoint function to the 'binnedInc' column
df['binnedInc_midpoint'] = df['binnedInc'].apply(get_midpoint)

# Dropping the binnedInc column
df = df.drop('binnedInc', axis=1)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3047 entries, 0 to 3046
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   avgAnnCount              3047 non-null   float64
 1   avgDeathsPerYear         3047 non-null   int64
 2   TARGET_deathRate         3047 non-null   float64
 3   incidenceRate            3047 non-null   float64
 4   medIncome                3047 non-null   int64
 5   popEst2015               3047 non-null   int64
 6   povertyPercent           3047 non-null   float64
 7   studyPerCap              3047 non-null   float64
 8   MedianAge                3047 non-null   float64
 9   MedianAgeMale            3047 non-null   float64
 10  MedianAgeFemale          3047 non-null   float64
 11  AvgHouseholdSize         3047 non-null   float64
 12  PercentMarried           3047 non-null   float64
 13  PctNoHS18_24             3047 non-null   float64
 14  PctHS18_24               3047 non-null   float64
 15  PctBachDeg18_24          3047 non-null   float64
 16  PctHS25_Over             3047 non-null   float64
 17  PctBachDeg25_Over        3047 non-null   float64
 18  PctEmployed16_Over       3047 non-null   float64
 19  PctUnemployed16_Over     3047 non-null   float64
 20  PctPrivateCoverage       3047 non-null   float64
 21  PctPrivateCoverageAlone  3047 non-null   float64
 22  PctEmpPrivCoverage       3047 non-null   float64
 23  PctPublicCoverage        3047 non-null   float64
 24  PctPublicCoverageAlone   3047 non-null   float64
 25  PctWhite                 3047 non-null   float64
 26  PctBlack                 3047 non-null   float64
 27  PctAsian                 3047 non-null   float64
 28  PctOtherRace             3047 non-null   float64
 29  PctMarriedHouseholds     3047 non-null   float64
 30  BirthRate                3047 non-null   float64
 31  binnedInc_midpoint       3047 non-null   float64
dtypes: float64(29), int64(3)
memory usage: 761.9 KB

In [16]:
# Function for splitting the data into Train, Validation and Test sets and saving them in 3 seperate csv files
# Splitting the dataset into 80% train, 10% validation and 10% test sets
def split_and_save_data(df, train_set_ratio=0.8, validation_set_ratio=0.1, test_set_ratio=0.1):

    # Splitting the dataframe into train dataframe and remaining (validation + test) dataframe
    train_df, remaining_df = train_test_split(df, test_size=(validation_set_ratio + test_set_ratio), random_state=42)

    # Splitting the remaining data into validation dataframe and test dataframe
    validation_df, test_df = train_test_split(remaining_df, test_size=test_set_ratio / (validation_set_ratio + test_set_ratio), random_state=42)

    # Saving the dataframes into csv files
    train_df.to_csv('train_cancer_reg.csv', index=False)
    validation_df.to_csv('validation_cancer_reg.csv', index=False)
    test_df.to_csv('test_cancer_reg.csv', index=False)

split_and_save_data(df)